# Generated by Django 3.2.11 on 2022-01-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightCode', models.TextField(max_length=7)),
                ('airlineName', models.CharField(max_length=15)),
                ('departureLocation', models.CharField(max_length=20)),
                ('arrivalLocation', models.CharField(max_length=15)),
                ('departureTime', models.TimeField()),
                ('arrivalTime', models.TimeField()),
                ('duration', models.CharField(max_length=4)),
                ('planeModel', models.CharField(default='', max_length=20, null=True)),
                ('totalSeats', models.IntegerField(default=40)),
                ('userID', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('flightStatus', models.BooleanField(null=True)),
                ('userID', models.IntegerField(null=True)),
                ('flightfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatClass', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('seatNumber', models.IntegerField(null=True)),
                ('booked', models.BooleanField(default=False)),
                ('flightdetailid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flightdetails')),
            ],
        ),
    ]
