# Generated by Django 3.2.11 on 2022-01-31 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4)),
                ('passengerID', models.IntegerField(null=True, unique=True)),
                ('flightDetailsID', models.IntegerField(null=True)),
            ],
        ),
    ]
